
name: Auto Update IPTV + EPG

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch latest playlist
        run: curl -o custom_playlist.m3u https://iptv-org.github.io/iptv/index.m3u
      - name: Fetch latest EPG
        run: curl -o guide.xml https://iptv-org.github.io/epg/guides/us.xml
      - name: Commit changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Bot"
          git add .
          git commit -m "Auto update playlist and EPG"
          git push
