name: Auto Update Playlist and EPG

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Update playlist and EPG
        run: |
          curl -o custom_playlist.m3u https://iptv-org.github.io/iptv/index.m3u
          curl -o guide.xml https://iptv-org.github.io/epg/index.xml
      - name: Commit and push
        run: |
          git config user.name "Auto Bot"
          git config user.email "autobot@example.com"
          git add .
          git commit -m "Automated update"
          git push
